PREFIX spav: <http://vocab.performing-arts.ch/>

WITH <http://example.com/tanzarchiv>

DELETE {
  ?s spav:r_isAssociatedWith_49 ?o .
}
INSERT { 
  ?s spav:isAssociatedWith ?conceptUri .
  
  ?conceptUri a spav:Person ;
    spav:label ?o .
}
WHERE {
    
  ?s spav:r_isAssociatedWith_49 ?o .
  BIND(URI(CONCAT("http://data.performing-arts.ch/person/", ENCODE_FOR_URI(?o))) AS ?conceptUri)

}