PREFIX spav: <http://vocab.performing-arts.ch/>

INSERT { GRAPH <http://example.com/tanzarchiv> {
  ?s a spav:RecordSet
}}
WHERE { GRAPH <http://example.com/tanzarchiv> { 
  ?s spav:level ?o
  
  FILTER( ?o IN("Dossier" ))
}}