java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Amateurtheater.ttl -o target/01.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_FesteHaeuser.ttl -o target/02.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Festivals.ttl -o target/03.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Festspiele.ttl -o target/04.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Foerderverein.ttl -o target/05.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Freilichtspiele.ttl -o target/06.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Museen.ttl -o target/07.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_ProduzentenTraegerAgenturen.ttl -o target/08.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Schulen.ttl -o target/09.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_TruppenProfi.ttl -o target/10.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_TruppenPuppentheater.ttl -o target/11.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Verbaende.ttl -o target/12.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_VorfasnachtRevueKulturnaechte.ttl -o target/13.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Datenbankurs_Zirkus.ttl -o target/14.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_Plakat_alleAttribute.ttl -o target/15.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_RepGesamt_alleAttributeohneDokumente.ttl -o target/16.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_StammdatenSpielzeit.ttl -o target/17.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_ZSV.ttl -o target/18.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_audio.ttl -o target/19.nt
java -jar lib/RML-Processor-0.3x100.jar -m config/production_mapping_stc_professional.ttl -o target/20.nt
